<!-- BEGIN PAGE LEVEL STYLES -->
<?php 
   $this->headLink()
        ->appendStylesheet($this->basePath('/assets/plugins/select2/select2.css'))
        ->appendStylesheet($this->basePath('/assets/plugins/select2/select2-metronic.css'))
        ->appendStylesheet($this->basePath('/assets/plugins/data-tables/DT_bootstrap.css'))
?>
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN EXAMPLE TABLE PORTLET-->
					<div class="portlet box grey">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-edit"></i>User List
							</div>
							<div class="tools">
								<a href="javascript:;" class="collapse">
								</a>
								<a href="#portlet-config" data-toggle="modal" class="config">
								</a>
								<a href="/" class="reload">
								</a>
								<a href="javascript:;" class="remove">
								</a>
							</div>
						</div>
						<div class="portlet-body">
							<div class="table-toolbar">
								<div class="btn-group">
									<button id="sample_editable_1_new" class="btn green">
									Add New <i class="fa fa-plus"></i>
									</button>
								</div>
								<div class="btn-group pull-right">
									<button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
									</button>
									<ul class="dropdown-menu pull-right">
										<li>
											<a href="#">
												 Print
											</a>
										</li>
										<li>
											<a href="#">
												 Save as PDF
											</a>
										</li>
										<li>
											<a href="#">
												 Export to Excel
											</a>
										</li>
									</ul>
								</div>
							</div>
							<table class="table table-striped table-hover table-bordered" id="sample_editable_1">
							<thead>
							<tr>
							    <th>Id</th>
								<th>Username</th>
								<th>Full Name</th>
								<th>Email</th>
								<th>Role</th>
								<th>Status</th>
								<th>Edit</th>
								<th>Delete</th>
							</tr>
							</thead>
							<tbody>
							 <?php foreach ($records as $record) : ?>
                            	 <tr>
                                	 <td><?php echo $this->escapeHtml($record->getUserId());?></td>
                                	 <td><?php echo $this->escapeHtml($record->getUsername());?></td>
                                	 <td><?php echo $this->escapeHtml($record->getName());?></td>
                                	 <td><?php echo $this->escapeHtml($record->getEmail());?></td>
                                	 <td><?php echo $this->escapeHtml($record->getRoleId()->getRole());?></td>
                                	 <td><?php echo $this->escapeHtml($record->getStatusId()->getStatus());?></td>
                                	 <td><a class="edit" href="javascript:;">Edit</a></td>
                                	 <td><a class="delete" href="javascript:;">Delete</a></td>
                            	 </tr>
                             <?php endforeach; ?>
							</tbody>
							</table>
						</div>
					</div>
					<!-- END EXAMPLE TABLE PORTLET-->

<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="/assets/plugins/select2/select2.min.js"></script>
<script type="text/javascript" src="/assets/plugins/data-tables/jquery.dataTables.js"></script>
<script type="text/javascript" src="/assets/plugins/data-tables/DT_bootstrap.js"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="/assets/scripts/core/app.js"></script>
<script src="/assets/scripts/ajax/users.js"></script>
<?php 
    $this->inlineScript()
        ->appendFile($this->basePath('/assets/scripts/datatable/users.index.js'))
        ->appendFile($this->basePath('/assets/scripts/ajax/users.js'))
        ->appendFile($this->basePath('/assets/scripts/ajax/generic.js'))
?>
<?php $this->inlineScript()->captureStart() ?>
    jQuery(document).ready(function() {    
        App.init();
        TableEditable.init();
    });
<?php $this->inlineScript()->captureEnd() ?>