<?php
$form->setAttribute('action', $this->url('product_add', array('action' => 'add')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>

<div class="tab-pane active" id="tab_0">
    <div class="portlet box green">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-reorder"></i>Add New Product
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse">
                </a>
                <a href="#portlet-config" data-toggle="modal" class="config">
                </a>
                <a href="javascript:;" class="reload">
                </a>
                <a href="javascript:;" class="remove">
                </a>
            </div>
        </div>
        <div class="portlet-body form">
            <!-- BEGIN FORM-->
            <?php echo $this->form()->openTag($form); ?>

            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-4 control-label">Item Code</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('item_code')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Supplier Code</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('supplier_code')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">BL Code</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('bl_code')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Print Code</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('print_code')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Product Name</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('name')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Brand</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('brand')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Category</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('category')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Sub Category</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('subcategory')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Description</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('description')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Unit of Measurement</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('uom')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Enter Color</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('color')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Size</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('size')); ?>
                    </div>
                </div>

            </div>
            <div class="form-group">
                <label class="col-md-4 control-label">Weight</label>
                <div class="col-md-4">
                    <?php  echo $this->formRow($form->get('weight')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label">Supplier</label>
                <div class="col-md-4">
                    <?php  echo $this->formRow($form->get('supplier')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label">International Cost</label>
                <div class="col-md-4">
                    <?php  echo $this->formRow($form->get('international_cost')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label">Purchase Cost</label>
                <div class="col-md-4">
                    <?php  echo $this->formRow($form->get('purchase_cost')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label">Currency</label>
                <div class="col-md-4">
                    <?php  echo $this->formRow($form->get('currency')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label">Status</label>
                <div class="col-md-4">
                    <?php  echo $this->formRow($form->get('status')); ?>
                </div>
            </div>

            <div class="form-actions fluid">
                <div class="col-md-offset-3 col-md-9">
                    <?php  echo $this->formRow($form->get('submit')); ?>
                    <button type="button" class="btn default">Cancel</button>
                </div>
            </div>

            <!-- END FORM-->
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
