<?php
$form->setAttribute('action', $this->url('product_add', array('action' => 'del')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>

<div class="tab-pane active" id="tab_0">
    <div class="portlet box green">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-reorder"></i>Add New Product
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse">
                </a>
                <a href="#portlet-config" data-toggle="modal" class="config">
                </a>
                <a href="javascript:;" class="reload">
                </a>
                <a href="javascript:;" class="remove">
                </a>
            </div>
        </div>
        <div class="portlet-body form">
            <!-- BEGIN FORM-->
            <?php echo $this->form()->openTag($form); ?>

            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-4 control-label">Code</label>
                    <div class="col-md-4">
                        <!--							<input type="text" class="form-control" placeholder="Enter Code">-->
                        <?php  echo $this->formRow($form->get('code')); ?>

                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label">Name</label>
                    <div class="col-md-4">
                        <!--							<input type="text" class="form-control" placeholder="Enter Product Name">-->
                        <?php  echo $this->formRow($form->get('name')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Brand</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('brand_id')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Model</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('model')); ?>

                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Description</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('description')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label">Size</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('size')); ?>
                    </div>
                </div>

            </div>
            <div class="form-group">
                <label class="col-md-4 control-label">Weight</label>
                <div class="col-md-4">
                    <?php  echo $this->formRow($form->get('weight')); ?>
                </div>
            </div>


            <div class="form-group">
                <label class="col-md-4 control-label">Unit of Measurement</label>
                <div class="col-md-4">
                    <?php  echo $this->formRow($form->get('uom')); ?>
                </div>
            </div>



            <div class="form-group">
                <label class="col-md-4 control-label">Status</label>
                <div class="col-md-4">
                    <?php  echo $this->formRow($form->get('status')); ?>

                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label">Supplier</label>
                <div class="col-md-4">
                    <?php  echo $this->formRow($form->get('supplier_id')); ?>


                </div>
            </div>



            <div class="form-actions fluid">
                <div class="col-md-offset-3 col-md-9">
                    <?php  echo $this->formRow($form->get('submit')); ?>
                    <button type="button" class="btn default">Cancel</button>
                </div>
            </div>

            <!-- END FORM-->
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
